version: "3.9"
services:
  #creando los contenedores
  spring-citamedica-image:
    #indicando q use la imagen creada
    image: spring-citamedica-image
    #indicando su nombre
    container_name: spring-citamedica-container

    #crea la imagen por nosotros
    build:
      context: .
      dockerfile: Dockerfile

    #comunicarnos con lso contenedores a travez de los puertos
    ports:
      #mappea el puerto de mi local, con el del contenedor
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_datebase
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: lindapt
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volumen:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volumen:
  #permisistir datos con volumes